### ISSUE TITLE
WinPhone: ViewModel 'TViewModel' has no public parameterless constructor

### ISSUE THREAD

**Issue by sascha-schwegelbauer** [daniel-luberda/DLToolkit.PageFactory#1]
Hi,

using your PageFactory with an Windows Phone 8.0 Project, the Init()-Function crashes with the following exception:

An exception of type 'System.ArgumentException' occurred in DLToolkit.PageFactory.Forms.DLL but was not handled in user code

Additional information: ViewModel 'TViewModel' has no public parameterless constructor

Droid and iOS run fine.

Regards,
Sascha

**Comment by daniel-luberda** [comment]
Hi,

Does it happen for a simplest PageFactory example? Or only in your specific project (if yes, can you share some code)? I will have to investigate it. 

Thanks,
Daniel

**Comment by sascha-schwegelbauer** [comment]
Yes, it happens for really simple examples. Do you have a default example-project so I could use it?

**Comment by daniel-luberda** [comment]
I'll test it by myself first today and see what's causing it. The simplest project is here: http://daniel-luberda.github.io/20150922/Page-Factory-MVVM-library-for-Xamarin-Forms/#minimal-code-to-get-it-working

**Comment by daniel-luberda** [comment]
It should be fixed here: https://www.nuget.org/packages/DLToolkit.PageFactory.Forms/
Can you try it?
