### ISSUE TITLE
Generalize Navigationcontainers / New features

### ISSUE THREAD

**Issue by escamoteur** [daniel-luberda/DLToolkit.PageFactory#11]
Hi Daniel,

currently the InitCall only accepts a Navigationpage which is a Limitation if an App should have a MasterDetail or TabbedPage as Rootelement.

Also it's not clear how to create and Push ContainerPages higher up the Navigation Stack. 

Also we need a consistend way how to init these Containers with their child elements. One way could be to provide default ViewModels that have child properties/Collections that you have to register first, but that's a problem in the way that we currently only push ViewModelTypes. 

A look at the features of FreshMVVM may help as inspriation ;-) https://github.com/rid00z/FreshMvvm#multiple-navigation-services

E.g. the possibility to switch out the whole Navigationstack is pretty need.

Ways to solve this
- Use static registration with Lazy creation methods for the viewmodel
- Allow to provide ViewModel Instances when pushing Pages
- Having additional InitMethods/PushMethods that allow to provide Child viewModelTypes

What do you think

Best
Thomas

P.S.: You may say, why don't you just use FreshMVVM? The reason is that PageFactory is even lighter and as such ideal to combine with RxUI. Also  as comfortable all the IoC and convention basing is it eats up to many resources especially at app startup.

**Comment by daniel-luberda** [comment]
Upcoming release will be a major one, so it's a good occasion to do some API changes / refactorings. Some my thoughts: 
- Change PageFactory Init method, to contain any `IBasePage` object
- Remove existing navigation methods and replace them with `IBasePage` extensions. Internal methods will use Page `Navigation` properties as a navigation. 
- Add page cache `keys` support, eg: `GetPageFromCache<TViewModel>("someKey")`
- Add page cache auto-removal after a certain duration. 

+1 for: 

> Use static registration with Lazy creation methods for the viewmodel
> Allow to provide ViewModel Instances when pushing Pages
> Having additional InitMethods/PushMethods that allow to provide Child viewModelTypes

**Comment by daniel-luberda** [comment]
> P.S.: You may say, why don't you just use FreshMVVM? The reason is that PageFactory is even lighter and as such ideal to combine with RxUI. Also as comfortable all the IoC and convention basing is it eats up to many resources especially at app startup.

I'm not worried to do some changes / modifications / improvements, especially if want to collaborate on this. Performance is also very important to me.

**Comment by escamoteur** [comment]
Yes, I really like to contribute as I need a solid foundation for my next projects.
If you tell me what I can do I'm happy to help

**Comment by daniel-luberda** [comment]
That's great. At first, we could think of API rewrites and features which should be implemented. Do you have any ideas?

**Comment by escamoteur** [comment]
I think one important decission will be if we keep the automatic 
Assembly discovery or switch to manual?

Manual registration has also the advantage that I can switchout the 
PageClass e.g. for bigger screens on the other side it's additional 
work.

------ Originalnachricht ------
Von: "Daniel Luberda" notifications@github.com
An: "daniel-luberda/DLToolkit.PageFactory" 
DLToolkit.PageFactory@noreply.github.com
Cc: "escamoteur" thomas@burkharts.net; "Author" 
author@noreply.github.com
Gesendet: 02.10.2016 16:23:09
Betreff: Re: [daniel-luberda/DLToolkit.PageFactory] Generalize 
Navigationcontainers (#11)
