### ISSUE TITLE
How do we work together?

### ISSUE THREAD

**Issue by escamoteur** [daniel-luberda/DLToolkit.PageFactory#13]
Hi Daniel,

I'm just starting with contributing to OSS projects, so I have no experience yet how to go along. Should I continue working with PRs? Or just create new branches when I make changes and you merge?
Best
Thomas

**Comment by daniel-luberda** [comment]
For me it doesn't matter, just choose the way you're more comfortable with. I changed some code now already. I think I can make a new branch for it, so you could see my changes, then I'll try to merge with your rx PR.

**Comment by escamoteur** [comment]
I thinks PRs have the benefit of the code review feature of github. 
Don't know if this is supported with branches

------ Originalnachricht ------
Von: "Daniel Luberda" notifications@github.com
An: "daniel-luberda/DLToolkit.PageFactory" 
DLToolkit.PageFactory@noreply.github.com
Cc: "escamoteur" thomas@burkharts.net; "Author" 
author@noreply.github.com
Gesendet: 02.10.2016 16:26:18
Betreff: Re: [daniel-luberda/DLToolkit.PageFactory] How do we work 
together? (#13)
