### ISSUE TITLE
Implementationdiscussion

### ISSUE THREAD

**Issue by escamoteur** [daniel-luberda/DLToolkit.PageFactory#14]
Why did you use this ConditionalWeakTable? That's one of the things I don't understand?

**Comment by daniel-luberda** [comment]
That table contains all pages references that were created or used within PageFactory methods. It must be a `ConditionalWeakTable` to allow them to be collected by garbage collector, we don't want to keep any references. Pages that we want to cache are stored in a `Dictionary`.

**Comment by escamoteur** [comment]
Which page references do we have to store that do not get into the cache?
Btw. you can also find me on slack https://xamarinchat.herokuapp.com/

or skype thomasburkhart  if discussion would be easier

**Comment by daniel-luberda** [comment]
We could have both (eg. add a param which disables automatic assemblies discovery).

> I think one important decission will be if we keep the automatic
> Assembly discovery or switch to manual?
> 
> Manual registration has also the advantage that I can switchout the
> PageClass e.g. for bigger screens on the other side it's additional
> work.
