### ISSUE TITLE
XAML Pages not working with Xamarin 4

### ISSUE THREAD

**Issue by ChrisWay** [daniel-luberda/DLToolkit.PageFactory#2]
Just found your library, it looks great, but I'm having trouble using XAML views with the latest stable version of Xamarin Forms. I'm trying to use your simple Hello World example but it will not compile with a XAML view, using a view created in code works fine. These are the errors Visual Studio gives when building. I've [uploaded the project](https://github.com/ChrisWay/PFTest) I have made, I'm not sure whether I have missed something obvious or it's an issue with the new version of Xamarin.

| Severity | Code | Description | Project | File | Line |
| --- | --- | --- | --- | --- | --- |
| Error | CS0263 | Partial declarations of 'HelloPage' must not specify different base classes | PFTest | E:\VS Projects\PFTest\PFTest\PFTest\HelloPage.xaml.cs | 12 |
| Error | CS0234 | The type or namespace name 'PFTest' does not exist in the namespace 'Xamarin.Forms' (are you missing an assembly reference?) | PFTest | E:\VS Projects\PFTest\PFTest\PFTest\obj\Debug\PFTest.HelloPage.xaml.g.cs | 17 |
| Error | CS0311 | The type 'PFTest.HelloPage' cannot be used as type parameter 'TView' in the generic type or method 'Extensions.LoadFromXaml<TView>(TView, Type)'. There is no implicit reference conversion from 'PFTest.HelloPage' to 'Xamarin.Forms.BindableObject'. | PFTest | E:\VS Projects\PFTest\PFTest\PFTest\obj\Debug\PFTest.HelloPage.xaml.g.cs | 21 |

**Comment by daniel-luberda** [comment]
@ChrisWay Hi! I just looked at your code and it seems fine. Didn't have time to test it with XF 2.0 though. 

There's a simple example project, just clone this: https://github.com/daniel-luberda/DLToolkit.Forms.Controls

and try to run sample app FlowListViewExpandPage.xaml is a page written in xaml. Could you test it?

**Comment by daniel-luberda** [comment]
If it won't help the fast workaround would be to use this code: 

```C#
namespace PFTest
{
    public partial class HelloPage : HelloPageTyped
    {
        public HelloPage() {
            InitializeComponent();
        }
    }
    
    public class HelloPageTyped : PFContentPage<HelloViewModel>
    {
        public HelloPage() {
        }
    }
}
```
```XML
<?xml version="1.0" encoding="utf-8" ?>
<local:HelloPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="PFTest.HelloPage"
    xmlns:local="clr-namespace:PFTest">
  <ContentPage.Content>
    <Label Text="{Binding HelloLabelText}" />
  </ContentPage.Content>
</local:HelloPage>
```

**Comment by daniel-luberda** [comment]
**Another one possible solution is to use:**

``` XML
<?xml version="1.0" encoding="utf-8" ?>
<pf:PFContentPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="PFTest.HelloPage"
    xmlns:pf="clr-namespace:DLToolkit.PageFactory"
    xmlns:local="clr-namespace:PFTest"
    x:TypeArguments="local:HelloViewModel">
  <ContentPage.Content>
    <Label Text="{Binding HelloLabelText}" />
  </ContentPage.Content>
</pf:PFContentPage>
```

**Comment by daniel-luberda** [comment]
Please let me now what worked for you :)

**Comment by ChrisWay** [comment]
Thanks @daniel-luberda, I'll give these suggestions a try later and get back to you.

**Comment by ChrisWay** [comment]
The thing that fixed it was adding in an `xmlns` for the viewmodel namspace and using that in `x:TypeArguments`. I've pushed that change to my example project above. Thanks for your help! :+1:

**Comment by daniel-luberda** [comment]
Ok :) Thanks @ChrisWay  for checking it. I'll update docs to include `xmlns` namespaces.
