### ISSUE TITLE
Should Navigation interception not being done by the PageModel

### ISSUE THREAD

**Issue by escamoteur** [daniel-luberda/DLToolkit.PageFactory#20]
Hi Daniel,

while documenting just came the thought is it not against MVVM if Navigation interception is done be the View?

Cheers
Thomas

**Comment by daniel-luberda** [comment]
That's true. We should add those interfaces support to page models too. That way, if the page or page model implements navigation interception interface, it will be handled.

**Comment by escamoteur** [comment]
yep. Are you come on Slack?

**Comment by daniel-luberda** [comment]
Done
