### ISSUE TITLE
Should we remove the page creation extensions from the Page extensions?

### ISSUE THREAD

**Issue by escamoteur** [daniel-luberda/DLToolkit.PageFactory#22]
Hi @daniel-luberda,

while writing the wiki I just stumbled upong the GetPage... and ...Cache..  methods in PageExtensions.cs

Don't we hurt MVVM principle in offering them? Do we really need them?

Cheers
Thomas

**Comment by daniel-luberda** [comment]
I think we need them. They are used for creating `TabbedPages` and similar. 

``` C#
tabbedPage.Children.Add(this.GetPageAsNewInstance<SomePageModel>());
// etc
```

**Comment by escamoteur** [comment]
yeah, I see the ContainerPages are different. you cannot easyly do it from the PageModel.
