### ISSUE TITLE
Should we really include Behaviours and Logging into the base nuget?

### ISSUE THREAD

**Issue by escamoteur** [daniel-luberda/DLToolkit.PageFactory#23]
@daniel-luberda 

I'm wondering if we should create separate nuget for such nice helpers, there may be more over time.

So maybe something like what Michael Ridland did with his FreshEssentials might be a better approach.

What to you think?

**Comment by daniel-luberda** [comment]
IMO `Logging` is handy in core. 

Behavior which I added is in `Xamarin.Forms` project, so it won't harm to have it there. I didn't have any intentions to add more behaviors, but this one is very commonly used and handy (turns events into commands -> helps with binding -> which is MVVM related).

**Comment by escamoteur** [comment]
ok
