### ISSUE TITLE
Not an issue but a comment

### ISSUE THREAD

**Issue by FrancoisM** [daniel-luberda/DLToolkit.PageFactory#3]
Great Library!
However, by design it is impossible to create a BasePage class. For example, I have to repeat these lines in every Page and I whish I could put them in a common base class.

NavigationPage.SetHasNavigationBar(this, false);
BackgroundColor = Color.FromHex(Settings.TemplateBgColor);

**Comment by daniel-luberda** [comment]
Thanks. I think it could be solved. Eg. algorithm that instantiates view model could take the most derived one Page, etc. I have to think about it a little.

**Comment by daniel-luberda** [comment]
The currently possible approach is to **create own IBasePage implementation** as here: 

https://github.com/daniel-luberda/DLToolkit.PageFactory/blob/master/DLToolkit.PageFactory.Forms/PFContentPage.cs

and add your logic there. It would work.

**Comment by FrancoisM** [comment]
Tks.
Also, by design as well, view models can't be instancied with parameters :-(
In my simplest MVVM implementation (nothing compared to yours lol) I assign a view model to a page whereas you assign a page to a view model. Why this approach?

**Comment by daniel-luberda** [comment]
PageFactory was created with simplicity in mind. Personally, I try to avoid using models with constructors with parameters, they tend to be problematic when doing some serialization, instantiation with Activator, etc. 

On the other hand, view model constructors with parameters handling could be added (it's definitely possible).

**Comment by daniel-luberda** [comment]
BTW: it's not that PageFactory ViewModels can't have constructors with a parameters. They can. The only current requirement is to also have a parameterless constructor. You could have another constructors, then instantiate viewModel and just call yourPage.ReplaceViewModel method (also inside Page constructor). It will also work.

**Comment by daniel-luberda** [comment]
Added ViewModels with non-parameterless constructors support: https://github.com/daniel-luberda/DLToolkit.PageFactory/commit/09734be3e92cd461fc453e6224d9aa2180c761cb

If you want to use ViewModels with non-default constructor, you'll have to override Page's ViewModelInitializer method and return default instance of your view model there (needed for its auto-instantiation)

**Comment by daniel-luberda** [comment]
@FrancoisM With this: https://github.com/daniel-luberda/DLToolkit.PageFactory/commit/2ebac8f34a884e4545bee8fec276abd0a257a1e7, you can now inherit pages, eg: 

```
public class SimpleFirstPage : SimpleFirstPageBase<SimpleFirstViewModel>
{
    public SimpleFirstPage()
    {
        this.SetBinding<SimpleFirstViewModel>(Page.TitleProperty, v => v.PageTitle);

        var button = new Button() {
            HorizontalOptions = LayoutOptions.FillAndExpand,
            VerticalOptions = LayoutOptions.FillAndExpand,
            Text = "Open Second Page"
        };
        button.SetBinding<SimpleFirstViewModel>(Button.CommandProperty, v => v.OpenPageCommand);

        Content = button;
    }
}

public class SimpleFirstPageBase<TViewModel> : PFContentPage<TViewModel> where TViewModel : class, INotifyPropertyChanged
{
    public SimpleFirstPageBase()
    {
        BackgroundColor = Color.White;
    }
}
```
