### ISSUE TITLE
UWP Fails to Open User Interface

### ISSUE THREAD

**Issue by runarj** [daniel-luberda/DLToolkit.PageFactory#36]
During startup, in Epigent.RxToDo.App, I call GetPageFromCache to get a page. However, the page’s content is null (myPage.Content = null). When the UI opens, no content is shown.

I use version 1.0.1.

Could there be a problem with UWP? I showed the problem to @escamoteur , and he suspected this might be the case.

I have published the solution [here](https://github.com/runarj/Epigent.RxToDo/commit/86d05fb96f9fed5e0aef839a324309c43466236c).

**Comment by daniel-luberda** [comment]
@runarj I just created a sample Windows UWP project, it works just fine. See this: https://github.com/xamvvm/xamvvm/tree/master/examples/ExamplesForms/WinUWP

![screen shot 2016-12-28 at 21 48 25](https://cloud.githubusercontent.com/assets/13569983/21531360/bb92ee3e-cd47-11e6-96e8-fade45f84baf.png)
