### ISSUE TITLE
XamvvmMockFactory.TargetPageModel is null when PopPageAsync is called

### ISSUE THREAD

**Issue by GiusepeCasagrande** [daniel-luberda/DLToolkit.PageFactory#37]
Hi, 

I'm trying to unit test my ViewModels and assert some navigation flow that I have on my app, but for a unknown reason to me the XamvvmMockFactory.TargetPageModel is null even when XamvvmMockFactory.LastActionSuccess is true;

I have replicated the issue on the ExampleUnitTests.Droid, here is the snipped: 

```c#
        [Fact]
        public async Task DetailButtonCommand()
        {

            var mainPageModel = new MainPageModel();

            mainPageModel.DetailButtonCommand.Execute("red");

            Assert.True(XamvvmMockFactory.LastActionSuccess);
            Assert.Equal(XamvvmMockFactory.XammvvmAction.PagePushed, XamvvmMockFactory.LastAction);
            Assert.IsType<DetailPageModel>(XamvvmMockFactory.TargetPageModel);
            Assert.Equal("red", ((DetailPageModel) XamvvmMockFactory.TargetPageModel).Text);

            await XamvvmMockFactory.TargetPageModel.PopPageAsync(false);
            Assert.True(XamvvmMockFactory.LastActionSuccess); // Is True
            Assert.Equal(XamvvmMockFactory.XammvvmAction.PagePopped, XamvvmMockFactory.LastAction);
            Assert.IsType<MainPageModel>(XamvvmMockFactory.TargetPageModel); // Should be MainPageModel, but is null
        }
```

**Comment by escamoteur** [comment]
Yep, I just checked. If we would like to include this we would need to add the full PageStackSimulation into the MockFactory

giusepe [2:21 PM]  
I mean, right now the Mock doesn’t have a stack (edited)
escamoteur [2:22 PM]  
yep

[2:22]  
as you normally only Test single Actions on a PageModel it won't cross more than one page level
I think this would go beyond UnitTests but automated UITests

You have to keep in mind that Pages are more or less stateless besides their PM (edited)
it doesn't interested them from where they got pushed not where they get back
sure you can test if you Page get's popped or another Page Pushed in reaction to some event
