### ISSUE TITLE
Xamvvm needs correct dependencies in NuGet

### ISSUE THREAD

**Issue by speaker** [daniel-luberda/DLToolkit.PageFactory#38]
Xamvvm.forms should depend on Xamvvm.core in NuGet

**Comment by escamoteur** [comment]
Same for XamvvmReactiveUI should pull in Forms and Core

**Comment by speaker** [comment]
Editing bug for a general dependency update

**Comment by daniel-luberda** [comment]
@speaker 
Currently, Xamarin.Forms nuget contains also `Xamvvm.Core ` dlls, so it's not needed to also add `Xamvvm.Core` nuget - it is only useful for people which want to create custom platform implementations. 

We can modify nuspec and add `Xamvvm.Core` as a dependency for future versions to avoid confusion.

**Comment by escamoteur** [comment]
Also we have to add dependencys to the RxUI version

**Comment by speaker** [comment]
@daniel-luberda Ok. When I was loading the packages I was told that Xamvvm.forms needed  Xamvvm.core.
