### ISSUE TITLE
Add a simple dependency service

### ISSUE THREAD

**Issue by daniel-luberda** [daniel-luberda/DLToolkit.PageFactory#39]
Injecting services through ViewModel / Page constructor became a standard for many frameworks. I think we should also have it. What are your opinions about it? 

```C#
public class MainPageModel : BasePageModel
{
  public MainPageModel(ISomeService someService)
  {
     // someService is automatically injected with a correct previously registered implementation
  }
}
```

**Comment by escamoteur** [comment]
would you use any existing ?
or can we open a way so that people can use the IOC they want?

If it does not hit our performace if not used we should add it.

**Comment by daniel-luberda** [comment]
https://github.com/xamvvm/xamvvm/wiki/IOC
