### ISSUE TITLE
Thinking of using this...How does it compare to FreshMVVM

### ISSUE THREAD

**Issue by ghost** [daniel-luberda/DLToolkit.PageFactory#4]
Besides letting me use my own IOC (DryIOC in my case), what are some differences between this and FreshMVVM?

**Comment by daniel-luberda** [comment]
FreshMVVM is quite nice MVVM framework. What comes to my mind is: 
- PageFactory has a Page/ViewModel caching and reusing mechanism. It could result in more responsive UI experience. You don't have to create Page instance every time you want to push it, etc. See demos: [link1](https://github.com/molinch/FFImageLoading/tree/master/samples/ImageLoading.Forms.Sample) [link2](https://github.com/daniel-luberda/DLToolkit.PageFactory/tree/master/Examples) - just clone, build and run
- PageFactory doesn't use any dependency injection. 
- PageFactory methods/classes are strongly typed, no dealing with `object` (not including messaging where parameter and sender are objects) 
- FreshMVVM forces you to use FreshBasePageModel (correct me if I'm wrong), with PageFactory you're not limited to any concrete implementation of Pages and ViewModels. You could use a provided ones, or just implement needed interfaces, eg. `INotifyPropertyChanged` or `IBaseMessagable` (if you need to use ViewModel messaging). The minimal requirement is to implemented only  `INotifyPropertyChanged` for viewmodels
- PageFactory has a basic INotifyPropertyChanged implementations out of the box, so you can use it right away. 
- PageFactory has messaging support (Page-Page, Page-ViewModel, ViewModel-Page, ViewModel-ViewModel)
- You're not limited to one IPageFactory implementation, XamarinFormsPageFactory is just an implementation, you can create your own. 
- PageFactory has a fluent API, eg: 

```
PageFactory.GetMessagablePageFromCache<SimpleSecondViewModel>()
                    .ResetViewModel()
                    .SendMessageToViewModel("ViewModelTestMessage", sender: this, arg: Guid.NewGuid())
                    .SendMessageToPage("PageTestMessage", sender: this, arg: Guid.NewGuid())
                    .PushPage();
```

**Comment by daniel-luberda** [comment]
Whole IPageFactory implementation is here: https://github.com/daniel-luberda/DLToolkit.PageFactory/blob/master/DLToolkit.PageFactory.Forms/XamarinFormsPageFactory.cs

It's the only needed thing to make your own IPageFactory which you could use with this lib and access all the features.

**Comment by ghost** [comment]
@daniel-luberda  thank you. Looks like this also has predefined nav methods like tabbed and master detail. Is there an example of such usage somewhere?

**Comment by daniel-luberda** [comment]
@robertbaker No problem. If you have any questions, just ask. There isn't any example anywhere but I'll create one and let you know. It's basically the same as with pure Xamarin.Forms:
- All that is different that you use `PFContentPage` (and others `PF*`) as child pages. 
- You can create their instances manually: `Children.Add(new MyPage())` - PageFactory will be aware of it and handle all the ViewModels initialization, etc
- You can use PageFactory methods to create them: 
  - `Children.Add(PF.Factory.GetPageAsNewInstance<TViewModel>())`
  - etc...
- The same with NavigationPages... just use PFNavigationPage or its derivatives. 
- `PF.Factory` is just a global static instance of initialized `IPageFactory` - it's useful when using `pure` ViewModels

PageFactory is currently `Xamarin.Forms` specific, but it could be extended to another platforms.

**Comment by daniel-luberda** [comment]
Another advice about tabbed and master detail pages:
- Be sure to not use cached page instance in multiple places, eg. one as a MasterDetail child and the second one as a pushed page(without a master). If you need to do something like this:
  - For MasterDetail child use: PageFactory.GetCachedPage
  - for all the additional pages: PF.Factory.GetPageAsNewInstance or create and handle additional instances by yourself
  - The same rule applies to pure Xamarin.Forms

**Comment by ghost** [comment]
@daniel-luberda Does this do Automatic wiring of BindingContext
Automatic wiring of Page events?

**Comment by daniel-luberda** [comment]
Yes, if you use PageFactory navigation, you don't need to worry about anything. ViewModels are automatically wired and initialized when instance of a page is created (doesn't matter how).

**Comment by daniel-luberda** [comment]
BTW: Pages have ViewModelinitializer method which you could override to change the way how a page initializes its ViewModel. It's needed for ViewModels without default constructor (if you won't do that you'll get an excption when initializing),

**Comment by ghost** [comment]
I recommend you put this in your readme as a comparison. Thanks!

**Comment by daniel-luberda** [comment]
I think I could prepare something :) Thanks!
