### ISSUE TITLE
What is the purpose of RegisterNavigationPage in App.xaml.cs?

### ISSUE THREAD

**Issue by markti** [daniel-luberda/DLToolkit.PageFactory#40]
The following code is in your sample application's code. 

          factory.RegisterNavigationPage<MainNavigationPageModel>(() => this.GetPageAsNewInstance<MainPageModel>());
            XamvvmCore.SetCurrentFactory(factory);
            MainPage = this.GetPageFromCache<MainNavigationPageModel>() as Page;

It utilizes two classes that both inherit from BasePageModel. The first being "MainNavigationPageModel" and the second being "MainPageModel". It appears MainPageModel is the one injected as the view model for the MainPage.xaml and MainNavigationPageModel is used for basically nothing. Why is this? Why even have MainNavigationPageModel at all? 

The ultimate goal appears to be to set the MainPage property on the Application (essentially setting the Root Visual). Why not simply acquire the page using MainPageModel? Since MainPage.xaml is already decorating itself with the IBasePage<MainPageModel> interface?

I ask because I'd like my start page to do something that requires hitting a web service and I'd like to initiate that outside the View Model's constructor (as is the method in the sample project's MainPageModel). However I have been unable to find a way to do that.

**Comment by daniel-luberda** [comment]
`Register` methods are mainly just a convenience helpers. They are mainly used to register navigation / multi pages, etc. 

This: 

```C#
factory.RegisterNavigationPage<MainNavigationPageModel>(() => this.GetPageAsNewInstance<MainPageModel>());
```

Replaces this: 

```C#
public class MainNavigationPage : NavigationPage, IBasePage<MainNavigationPageModel>
{
    // Notice calling base constructor which sets main page for the navigation you're creating
    public MainNavigationPage() : base(this.GetPageAsNewInstance<MainPageModel>())
    {

    }
}
```

Both approaches will work fine. 

> The ultimate goal appears to be to set the MainPage property on the Application (essentially setting the Root Visual). Why not simply acquire the page using MainPageModel? Since MainPage.xaml is already decorating itself with the IBasePage interface?

To enable navigation in Xamarin.Forms you have to use navigation pages as containers for all other pages. It's a Xamarin.Forms requirement. When you want to push whole navigation stack, you must push whole navigation page. The same applies to TabbedPages, etc. - you want to push whole TabbedPage, but it can contain many other pages as Tab1Page, Tab2Page, etc. It's just how pure Xamarin.Forms navigation works. 

> I ask because I'd like my start page to do something that requires hitting a web service and I'd like to initiate that outside the View Model's constructor (as is the method in the sample project's MainPageModel). However I have been unable to find a way to do that.

One of the solutions could be: 

```C#
var page = this.GetPageFromCache<YourPageModel>();
await page.GetPageModel().SomeInitializationMethodAsync();
this.PushPage(page);
```

**Comment by markti** [comment]
Ok,  so I did the following:


            factory.RegisterNavigationPage<MainNavigationPageModel>(() => this.GetPageAsNewInstance<SectionViewModel>());
            XamvvmCore.SetCurrentFactory(factory);
            var page = this.GetPageFromCache<SectionViewModel>();
            page.GetPageModel<SectionViewModel>().Refresh();

            MainPage = page as Page;

Any reason why I still need to use MainNavigationPageModel?

**Comment by markti** [comment]
It appears that unless TNavPage and TActualPage not different classes then I can't navigate. I guess what you are saying is 'Yes, TNavPage and TActualPage must be different due to a limitation in Xamarin.Forms and how NavigationPages are handled in the framework."

            factory.RegisterNavigationPage<TNavPage>(() => this.GetPageAsNewInstance<TActualPage>());
            XamvvmCore.SetCurrentFactory(factory);
            MainPage = this.GetPageFromCache<TNavPage>() as Page;

Is that what you're saying?

**Comment by markti** [comment]
I used the TNavPage and TActualPage to get my page to start.

            var factory = new XamvvmFormsFactory(this);
            factory.RegisterNavigationPage<TNavPage>(() => this.GetPageAsNewInstance<TActualPage>());
            XamvvmCore.SetCurrentFactory(factory);
            MainPage = this.GetPageFromCache<TNavPage>() as Page;

It sets TActualPage as the start up page but now I need to invoke a method called "Refresh" on it which calls my web service.

I tried your code that your provided above...

var page = this.GetPageFromCache<TActualPage>();
await page.GetPageModel().SomeInitializationMethodAsync();
this.PushPage(page);

The method does invoke. But just not on an instance of the TActualPage that is currently displayed. I suspect when the above statements are executed I'm getting a new version of TActualPage not the instance that was created when the application initialized TNavPage.

**Comment by markti** [comment]
This is what I tried:

            factory.RegisterNavigationPage<MainNavigationPageModel>(() => this.GetPageAsNewInstance<SectionViewModel>());
            XamvvmCore.SetCurrentFactory(factory);
            var page = this.GetPageFromCache<MainNavigationPageModel>();

            MainPage = page as Page;

            var sectionPage = this.GetPageFromCache<SectionViewModel>();
            var model = sectionPage.GetPageModel<SectionViewModel>();
            model.Refresh();


However, even though Refresh is invoked, it does not invoke on the same view model instance. I suspect that this has something to do with the delegate that I pass to RegisterNavigationPage calls "GetPageAsNewInstance<SectionView>" is not returning the same instance of the page as my later call to "this.GetPageFromCache<SectionView>". Possibly because the delegate hasn't fired yet to generate a new instance of the SectionViewModel so there is nothing in the cache yet so it will new up a new instance of the SectionViewModel before the MainNavigationPageModel is even initialized / rendered.

**Comment by daniel-luberda** [comment]
> However, even though Refresh is invoked, it does not invoke on the same view model instance. I suspect that this has something to do with the delegate that I pass to RegisterNavigationPage calls "GetPageAsNewInstance" is not returning the same instance of the page as my later call to "this.GetPageFromCache".

Yes, it would work if you change `GetPageAsNewInstance` to `GetPageFromCache`. I'll need to write some WIKI article about page caching. `FromCache` calls always try to reuse pages instances, `AsNewInstance` always return new instances. 

Another way:

```C#
var pageModel = new SomePageModel();
await pageModel.DoSomeStuffAsync();

// notice page model is set to your custom one:
var page = this.GetPageFromCache<MainPageModel>(pageModel); //or GetPageAsNewInstance
await this.PushPageAsync(page);
// OR:
var page = this.GetPageFromCache<MainPageModel>()
                    .SetPageModel(pageModel);
await this.PushPageAsync(page);
```
