### ISSUE TITLE
The Start Page should have an OnNavigatedTo that is invoked after the MainPage is set

### ISSUE THREAD

**Issue by markti** [daniel-luberda/DLToolkit.PageFactory#41]
Currently we can only perform load logic inside the constructor of the MainPage (as demonstrated by the Sample Project). We need a way to have a virtual OnNavigatedTo method invoked when navigation takes place.

For example, the sample has the following code:

            factory.RegisterNavigationPage<MainNavigationPageModel>(() => this.GetPageAsNewInstance<MainPageModel>());
            XamvvmCore.SetCurrentFactory(factory);
            MainPage = this.GetPageFromCache<MainNavigationPageModel>() as Page;

The implementation of MainPageModel should override a virtual method called OnNavigatedTo and it should get invoked when the page is navigated to.

**Comment by escamoteur** [comment]
That's already possible.  Please check the Wiki for Navigation - >NavigationInterception

**Comment by escamoteur** [comment]
That's already possible.  Please check the Wiki for Navigation - >NavigationInterception

**Comment by markti** [comment]
I don't see that in the wiki

**Comment by markti** [comment]
the wiki on this site

**Comment by markti** [comment]
I am inheriting from Xamvvm.BasePageModel which implements the INavigationInterceptors. However, none of those methods ever get invoked on the MainPageModel. Also, the documentation doesn't specify what is the equivalent of OnNavigatedTo

**Comment by markti** [comment]
It doesn't work on the Start Page (Main Page). 
![image](https://cloud.githubusercontent.com/assets/3155241/21662176/657f717a-d2a6-11e6-8a49-8f20aebd5eed.png)

![image](https://cloud.githubusercontent.com/assets/3155241/21662182/6eafd5aa-d2a6-11e6-99b7-0edecf9bf898.png)

![image](https://cloud.githubusercontent.com/assets/3155241/21662190/7aec14fa-d2a6-11e6-8fb6-c5bf9db8820d.png)

This is straight out of your sample code.

**Comment by daniel-luberda** [comment]
I replied to you, here: https://github.com/xamvvm/xamvvm/issues/42
