### ISSUE TITLE
Navigation Interception not working

### ISSUE THREAD

**Issue by markti** [daniel-luberda/DLToolkit.PageFactory#42]
None of these overrides fire when navigation takes place.

![image](https://cloud.githubusercontent.com/assets/3155241/21672767/86c9bbf0-d2f2-11e6-8747-b5c838206364.png)

**Comment by daniel-luberda** [comment]
Hi @markti,

Maybe it's something debugger related? Could include something like `System.Diagnostics.Debug.WrtieLine("PUSHED");` there?

**Comment by markti** [comment]
I think I found the problem. 

![image](https://cloud.githubusercontent.com/assets/3155241/21683044/9a702292-d325-11e6-82b2-598ff2e5b2cd.png)

In the above code snippet, 'pageToPush' is the View not the PageModel. I am expecting to implement INavigationInterceptors on the PageModel (ViewModel). I do this by inheriting from 'Xamvvm.BasePageModel' which implements INavigationInterceptors.

It seems rather puzzling that you would be looking for the interface on the view rather than the view model.

**Comment by daniel-luberda** [comment]
@markti True, it should be called for both. I'll add it now and release nuget.

**Comment by markti** [comment]
I pushed a fix but you can do it if you like. I have been adding a direct reference to your libraries so I can figure out what it's doing under the hood :)

**Comment by markti** [comment]
Glad to hear my understanding of your intent is correct. There is still the issue with navigation on the Start Page. The navigation interception doesn't work even with my fix.

**Comment by daniel-luberda** [comment]
Yes, I saw the PR. Great :) Thanks for catching that issue and making the PR 👍 

> There is still the issue with navigation on the Start Page.

I received a lot of issues/emails recently. Could you remind me what what the problem? I'll try to help.

**Comment by markti** [comment]
No worries man. The start page of your app when using Xamvvm has no way to call a method on the view model to initialize the page. So it only really allows someone to put a hard coded menu (like in your sample) as opposed to invoking some code that does something (e.g. calls a web service). I added the page intercept overrides on my start page but they aren't being picked up. It's related to the MainNavigationPageModel and the MainPageModel funkiness we've discussed.

**Comment by markti** [comment]
This is the code, maybe it will refresh your memory...

![image](https://cloud.githubusercontent.com/assets/3155241/21683869/38502338-d329-11e6-86d4-093f060ea60f.png)

**Comment by markti** [comment]
The problem stems from.

1. The start page is not stored in the cache so we can't obtain a reference to it afterwards.
2. The navigation events are not invoked after the start page is initialized and set as the MainPage.

**Comment by daniel-luberda** [comment]
> The navigation events are not invoked after the start page is initialized and set as the MainPage.

This should be fixed now. There were some additional fixes that needed to be done. Could you try the newest prerelease? (1.0.2.113)

**Comment by markti** [comment]
Hmm, I was using the code right off of GitHub...

**Comment by daniel-luberda** [comment]
Ah, I forgot that setting page as main page is not an navigation event.

**Comment by markti** [comment]
Did you fix it in a different branch? I've been refreshing to master... I have the latest bits from there.

**Comment by markti** [comment]
See my PR related to the subject. I didn't get the navigation hooks into the start page (it could be useful when you navigate BACK to the start page) but I at least enabled one to obtain a reference to the start page (I couldn't find a way to do this due to how GetPageAsNewInstance as NOT caching the page!)

**Comment by markti** [comment]
My solution was to cache the page created by GetPageAsNewInstance but to ensure that a NEW instance was created and anything with its key is blown away from the cache. Seems to work? 👍

**Comment by daniel-luberda** [comment]
> The start page is not stored in the cache so we can't obtain a reference to it afterwards.

If you use it with `GetPageFromCache` method it's stored in navigation just as any other page. You can get it with `GetPageFromCache<MainPageModel>()` method. Just replace `GetPageAsNewInstance<SectionViewModel>()` with `GetPageFromCache<SectionViewModel>()`.

You can also get it from NavigationStack of its main page: 

var sectionPage = `(NavigationPage)(GetPageFromCache<MainPageModel>)).Navigation.NavigationStack.First();`

**Comment by markti** [comment]
Ahh, so instead of using GetPageAsNewInstance in the app.xaml.cs I should use GetPageFromCache...if that's the case, why EVER use GetPastAsNewInstance? Why wouldn't GetPageAsNewInstance also cache the new instance it creates?

**Comment by daniel-luberda** [comment]
- When you want to push the same page type twice. You can't have two same instances pushed, you want them to be different instances. You can also achieve the same effect by using `GetPageFromCache` with different keys (parameter), but both pages would be cached. 
- There might be a case when you don't want the page to be cached at all (some heavy pages) and you can just simply use `GetPageAsNewInstance` which doesn't use cache at all.
- Only GetPageFromCache saves to / retrieves from cache. 
- `GetPageAsNewInstance` will always return a new instance which will be lost / garbage collected when isn't referenced anywhere.
