### ISSUE TITLE
Why after new update it gives me error on "GetPageModel()"?

### ISSUE THREAD

**Issue by palla89** [daniel-luberda/DLToolkit.PageFactory#45]
Hi,

I used till some minutes ago xamvvm without any problem. Now, after the last update, I can't compile anymore with errors.

this.GetPageModel() throws me an error: 'Gallerypage does not contain a definition for GetPageModel and no extension method 'GetPageModel' .....

**Comment by daniel-luberda** [comment]
Hi @palla89,

I just tested current nuget and it works for me: 

![screen shot 2017-01-05 at 17 49 57](https://cloud.githubusercontent.com/assets/13569983/21689077/7be62caa-d36f-11e6-8367-99be234dd0c3.png)


Could you give me what packages you installed? Maybe try to uninstall nuget & install once again, clean solution etc?

**Comment by palla89** [comment]
Thank you for your fast answer Daniel! After one hour of clean, reinstall and manual removing of the obj and bin folder, it started compiling again... Thank you for your awesome work!
