### ISSUE TITLE
Set BindingContext too in RxUIFactory

### ISSUE THREAD

**Issue by escamoteur** [daniel-luberda/DLToolkit.PageFactory#46]
We should not only set the ViewModel Property but also the BindingContext in RxUI implementation in case that someone wan't to use both bindings

**Comment by daniel-luberda** [comment]
Hi @escamoteur,

This method sets `BindingContext`: https://github.com/xamvvm/xamvvm/blob/master/source/Xamvvm.Forms.RxUI/XamvvmFormsRxUIFactory.cs#L16

Am I missing something?
