### ISSUE TITLE
QUESTIONS - If you want to ask anything about PageFactory - do it here. 

### ISSUE THREAD

**Issue by daniel-luberda** [daniel-luberda/DLToolkit.PageFactory#5]
QUESTIONS - If you want to ask anything about PageFactory - do it here :)

**Comment by escamoteur** [comment]
Hi Daniel,

could you explain a little bit more about the page caching? 
What exactly do you mean by caching? 
How long are pages cached?
Is there any support for saving App state, meaning rebuilding the pages when the App was removed and restarted?

It also would be great if you could explain a bit more in the documentation about the general approach that you use when you use PageFactory e.g. whats the purpose of the messaging system. 

Are there any other users besides you so far?
Would you recommend it at the current state to starte a new App development on it?

Can I use it in a commercial app?

I'm really impressed what you built there! 
Best
Thomas

**Comment by daniel-luberda** [comment]
Hi Thomas! Sure. 

> Could you explain a little bit more about the page caching? What exactly do you mean by caching? How long are pages cached?

When using `GetPageFromCache<TViewModel>()` or `GetMessagablePageFromCache<TViewModel>()` you always get the same page instance (you may treat is as a singleton) until you remove it from a cache with appropriate method. So, when you pop the page without removing it from cache it's still in memory and when you push it once again with `GetPageFromCache<TViewModel>().PushPage()` you'll get the same instance every time, nothing has to be initialized so it results in a better UI performance experience. 

> How long are pages cached?

By default they're never removed from cache. You can control it as you like. PageFactory pages offer additional Navigation interception methods as `PageFactoryPopped` override. So if you have some heavy pages which you don't want to cache you can just call `yourPage.RemovePageInstanceFromCache()` and it will be removed from cache (eg. in `OnDisappearing` or `PageFactoryPopped` page overrides or everywhere else you want). You can easily put this into your viewmodel logic too as every view model has access to its page with `GetPage()` extension method. 

Currently I'm also thinking about adding a new feature which will automatically remove pages from cache after specified `TimeSpan` that could be changed per page basis. 

> Is there any support for saving App state, meaning rebuilding the pages when the App was removed and restarted?

Not currently, but it's an interesting feature. The main problem is we need serialize view models and save  / load them from disk. The most of needed functionalities are already there. 

> It also would be great if you could explain a bit more in the documentation about the general approach that you use when you use PageFactory e.g. whats the purpose of the messaging system.

Yes, docs could definitely be expanded/updated. I'll think of it. In a nutshell, you may think of messaging system is a dependency free Xamarin.Forms MessagingCenter replacement which is even easier to use as you don't have to worry about subscribing / unsubscribing anything. You just know that every page (all pages are messagable) and every viewmodel which implements `IBaseMessagable` (default `BaseViewModel` does) can send/receive messages.

In most cases, I use it to pass data/parameters between pages or view models. eg. 
- Force some page to refresh its view model from another page
- Force some view model to refresh its state from another view model
- Send id from master view model to detail view model then refresh details view model data to reflect passed id and then push page and show it to user. 

> Are there any other users besides you so far? Would you recommend it at the current state to starte a new App development on it?

Yes, they're - but not many. I didn't advertise this framework much yet. You shouldn't be afraid of using it though because this lib is very very light. Xamarin.Forms IPageFactory implementation is just a one file! See: https://github.com/daniel-luberda/DLToolkit.PageFactory/blob/master/DLToolkit.PageFactory.Forms/XamarinFormsPageFactory.cs
so it's very easy to fix any bug... and it's possible to use custom build page factories too and still use all page factory features. (You can use your own custom IPageFactory implementations very easily)

> Can I use it in a commercial app?

Of course. It's apache licensed, so you can do whatever you like with it. 

> I'm really impressed what you built there! 

Thanks! If you have any questions - just ask.

**Comment by escamoteur** [comment]
Hi Daniel,
thanks a lot, I will give it a try, This whole way of almost completely decoupled programing is still very new to me (may be I'm getting old) and sometimes feels a bit like too much magic happening behind the scenes. But as you said, your framework is really really light weight and also I like that the binding of Views and Viewmodel is done at compile time and I define ist, not just based on file names.

As I already saw with your CachedImage I also appreciate your passion in supporting your work.

**Comment by escamoteur** [comment]
Hi Daniel,

why did you introduce your own CommandClass?

Also I am a bit worried about the performance of your SetField/GetField Method.Is it really worth always access a Dictonary just to automate the call for NotifyPropertyChanged?

Thanks
Thomas

**Comment by escamoteur** [comment]
Wouldn't it be more consequent to name BaseViewModel BasePageModel if you call the Views Pages?

There is one big limitation with this hard wiring Views and ViewModels. You can't use different Views on the same ViewModel (something named always as benefit of MVVM) or reuse a View with different VewModels

**Comment by daniel-luberda** [comment]
Hi @escamoteur,

> thanks a lot, I will give it a try, This whole way of almost completely decoupled programing is still very new to me (may be I'm getting old) and sometimes feels a bit like too much magic happening behind the scenes. But as you said, your framework is really really light weight and also I like that the binding of Views and Viewmodel is done at compile time and I define ist, not just based on file names.

I'm also not a fan of doing to much magic for simple things. 

> As I already saw with your CachedImage I also appreciate your passion in supporting your work.

Thanks, it's really nice to hear that from another developer! :)

> why did you introduce your own CommandClass?

Xamarin implementation needs Xamarin.Forms dependency. I wanted it to be a dependency free version of it. It's user choice if it should be used.

> Also I am a bit worried about the performance of your `SetField`/`GetField` method.Is it really worth always access a Dictonary just to automate the call for NotifyPropertyChanged?

Because of that, there're additional `SetField` and `GetField` methods `overrides` which **don't use Dictionary**. Also `BaseModel` class doesn't use Dictionary at all for performance reasons (for models, eg. items on lists you definitely don't want to use dictionares). In most of the situations, it's quite safe to use Dictionary on ViewModel though (it's usually not called many times).

**Comment by daniel-luberda** [comment]
> Wouldn't it be more consequent to name BaseViewModel BasePageModel if you call the Views Pages?

Actually, that's an interesting suggestion. I'll think of it. All in all Page is also a View. And `BaseViewModel` class **is just a helper class**. **You can use it or not - it's your decision**. PageFactory only requirement for a ViewModel is that it has to implement `INotifyPropertyChanged` interface (and also `IBaseMessagable` if it has to receive messages), so you can provide your own implementation.

> There is one big limitation with this hard wiring Views and ViewModels. You can't use different Views on the same ViewModel (something named always as benefit of MVVM) or reuse a View with different VewModels

True, but it's by design - PageFactory uses ViewModel navigation, so it forces page-view model binding. In my opinion you can use **inheritance** or **composition** to achieve desired results.
BTW: if you have any suggestions how to improve that - just write to me.

**Comment by escamoteur** [comment]
Is there any problem if I assign a async function to a PageFactoryCommand?

How do I override the Page event methods: OnAppearing(), OnBackButtonPressed() : Boolean,
OnDisappearing()?

**Comment by daniel-luberda** [comment]
> Is there any problem if I assign a async function to a PageFactoryCommand?

Everything should be working fine using `async`. Do you have any problems with it? 

> How do I override the Page event methods: OnAppearing(), OnBackButtonPressed() : Boolean,
> OnDisappearing()?

Just the same as in pure Forms. Can you elaborate?

**Comment by escamoteur** [comment]
Is it possible to create a inheritance hirachie for pages? 
I'm guessing no, because of the template approach.
With ViewModels this is no problem.

Do you see any way how to reuse page functionality for other pages?

**Comment by daniel-luberda** [comment]
Yes, it's possible. Algorithm chooses the most derived page type. See example here: https://github.com/daniel-luberda/DLToolkit.PageFactory/blob/master/Examples/Pages/PageInheritancePage.cs

**Comment by daniel-luberda** [comment]
You can also create you own `PFPageType` implementation. PageFactory doesn't use any concrete implementations, example here: https://github.com/daniel-luberda/DLToolkit.PageFactory/blob/master/DLToolkit.PageFactory.Forms/PFContentPage.cs

**Comment by escamoteur** [comment]
So I have to create my own base class as template and pass this on to e.g. PFContentPage, right?

**Comment by daniel-luberda** [comment]
Exactly. The simplest approach is to create something like this: 

```
public class MyCustomContentPage<TViewModel> : PFContentPage<TViewModel> where TViewModel : class, INotifyPropertyChanged
{
    public MyCustomContentPage()
    {
        // Your custom logic here
    }
}
```

and use it in xaml:

``` xml
<local:MyCustomContentPage/>
```

or, if you want to have more control (renderers stuff, etc), create your own `CustomPFContentPage` basing on this: https://github.com/daniel-luberda/DLToolkit.PageFactory/blob/master/DLToolkit.PageFactory.Forms/PFContentPage.cs

**Comment by escamoteur** [comment]
This works fine. 

I'm trying to add a base Xaml part to the base page but this seems not be possible.

```
<?xml version="1.0" encoding="utf-8" ?>
<pf:PFContentPage x:Name="this" xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pf="clr-namespace:DLToolkit.PageFactory"
             xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"  
             xmlns:TBGUI="clr-namespace:TBGUI;assembly=TBGUI"                  
             xmlns:local="clr-namespace:BREADy;assembly=EmbeddedResources"
             x:Class="BREADy.Views.DetailsBasePage"
             x:TypeArguments="local:ViewModels.DetailsBaseViewModel"
             >

  <ContentPage.Padding>
    <OnPlatform x:TypeArguments="Thickness"
                iOS="20, 40, 20, 20"
                Android="20, 20, 20, 20"
                WinPhone="20, 20, 20, 20" />
  </ContentPage.Padding>

    <ContentPage.Resources>
        <ResourceDictionary>
            <local:BooleanNegationConverter x:Key="not" />
        </ResourceDictionary>
    </ContentPage.Resources>


  <ContentPage.ToolbarItems>
    <TBGUI:BindableToolbarItem Name="{local:Translate Save}" 
                               Order="Primary" 
                               Priority="0"
                               Parent="{x:Reference this}"
                               IsVisible="{Binding SaveEnabled}"
                               Command ="{Binding SaveCommand}">
      <ToolbarItem.Icon>
        <OnPlatform x:TypeArguments="FileImageSource"
                    iOS="reload.png"
                    Android="ic_action_save.png"
                    WinPhone="Images/refresh.png" />
      </ToolbarItem.Icon>
    </TBGUI:BindableToolbarItem>
  </ContentPage.ToolbarItems>


</pf:PFContentPage>
```

This is the code behind:

```
using DLToolkit.PageFactory;
using System.ComponentModel;

namespace BREADy.Views
{
    public class DetailsBasePage<TViewModel> : PFContentPage<TViewModel> where TViewModel : class, INotifyPropertyChanged
    {
        public DetailsBasePage() { }
    }

```

But I now get an "The name InitalizeComponent does not exists" in the drived page:

```
    public partial class IngredientPage : DetailsBasePage<IngredientViewModel>
    {

        public IngredientPage ()
        {
            InitializeComponent();
        }

        public override bool PageFactoryPopping()
        {
            ViewModel.OnPagePopping();
            return base.PageFactoryPopping();
        }

        protected override bool OnBackButtonPressed()
        {
            ViewModel.OnPagePopping();
            return base.OnBackButtonPressed();

        }
    }
}

```

This is the corresponding Xaml:

```
<?xml version="1.0" encoding="utf-8" ?>
<local:Views.DetailsBasePage x:Name="this" xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pf="clr-namespace:DLToolkit.PageFactory"
             xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"  
             xmlns:TBGUI="clr-namespace:TBGUI;assembly=TBGUI"                  
             xmlns:local="clr-namespace:BREADy;assembly=EmbeddedResources"
             x:Class="BREADy.Views.IngredientPage"
             x:TypeArguments="local:ViewModels.IngredientViewModel"
             Title ="{local:Translate Ingredients}">

    <ContentPage.Content>
        <ScrollView  Orientation = "Vertical">    
            <StackLayout Orientation="Vertical">

              <BoxView Color="Transparent" HeightRequest="10"/>
              <BoxView Color="Gray" HeightRequest="1"/>
              <BoxView Color="Transparent" HeightRequest="10"/>

              <Label  Text="{local:Translate Name}" FontSize="Medium"/>
               <Entry x:Name="nameEntry" Text="{Binding Name}">
               </Entry>

              <BoxView Color="Transparent" HeightRequest="20"/>

               <Label Text="{local:Translate Description}" FontSize="Medium"/>
               <Editor Text="{Binding Description}"/>

               <ActivityIndicator IsVisible="{Binding IsSaving}" IsRunning="{Binding IsSaving}"
               VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" />

                </StackLayout>
            </ScrollView>
    </ContentPage.Content>


</local:Views.DetailsBasePage>

```

Could this work?

**Comment by daniel-luberda** [comment]
Instead of doing this: 

``` XML
<?xml version="1.0" encoding="utf-8" ?>
<pf:PFContentPage x:Name="this" xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pf="clr-namespace:DLToolkit.PageFactory"
             xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"  
             xmlns:TBGUI="clr-namespace:TBGUI;assembly=TBGUI"                  
             xmlns:local="clr-namespace:BREADy;assembly=EmbeddedResources"
             x:Class="BREADy.Views.DetailsBasePage"
             x:TypeArguments="local:ViewModels.DetailsBaseViewModel"
             >
<!-- rest of the code -->

</pf:PFContentPage>
```

Do this:

``` XML
<yourNamespace:DetailsBasePage x:Name="this" xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pf="clr-namespace:DLToolkit.PageFactory"
             xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"  
             xmlns:TBGUI="clr-namespace:TBGUI;assembly=TBGUI"                  
             xmlns:local="clr-namespace:BREADy;assembly=EmbeddedResources"
             x:Class="BREADy.Views.DetailsBasePage"
             x:TypeArguments="local:ViewModels.DetailsBaseViewModel"
             >
<!-- rest of the code -->

</yourNamespace:DetailsBasePage>
```

also make sure your DetailsBasePage.cs also has `DetailsBasePage` type

**Comment by escamoteur** [comment]
Same result.

This is my DetailsBasePage.cs

```
namespace BREADy.Views
{
    public class DetailsBasePage<TViewModel> : PFContentPage<TViewModel> where TViewModel : class, INotifyPropertyChanged
    {
        public DetailsBasePage() { }
    }
}

```

Perhaps for additional explanation. What I' trying is having a BasePage (DetailsBasePage) with an Xaml-Part without a <Content> part. 

From this I want to derive IngredientPage which is bound to IngredientsViewModel which is derived from DetailsBaseBaseViewModel.

**Comment by escamoteur** [comment]
If this is not possible, it's ok, then I will do the reusable GUI Part of the BasePage not in Xaml but in code.

**Comment by daniel-luberda** [comment]
If it's possible with Xamarin.Forms, it's definitely possible with PageFactory. From what I know, Xamarin.Forms doesn't fully support XAML Pages inheritance. There are some changes in 2.1 which could provide additional support for that, you could test it.

**Comment by escamoteur** [comment]
I now tried it with a minimal page and it looks like that it is not possible to have a Xaml Page with a Template class. As soon as I introduce the template parameter it doesn't compile anymore.
So Xaml Inheritance works, but not with templates.

**Comment by mcweekly** [comment]
Nice library! 

I'm wondering how do I trigger a display alert from the view model?

**Comment by ChrisWay** [comment]
Hi Daniel

What would be the best way of having a Tabbed Page as your base view and then loading in the content of each tab by specifying a view model?

**Comment by escamoteur** [comment]
Still alive?

**Comment by daniel-luberda** [comment]
@escamoteur  Yes, I think so. I use it in a few projects and didn't experience any issues. This repo isn't so popular though, so I didn't added any new features as I even don't know what are the needs. 

@mcweekly I would use ACR UserDialogs for that.

@ChrisWay 

Just create a page which inherits from `TabbedPage` and then:

``` C#
Children.Add(PF.Factory.GetPageFromCache<FirstTabPageModel>());
Children.Add(PF.Factory.GetPageFromCache<SecondTabPageModel>());
Children.Add(PF.Factory.GetPageFromCache<ThirdPageModel>());
```

and that's all

**Comment by GiusepeCasagrande** [comment]
Hey guys, @daniel-luberda and @escamoteur 

How do you use it with a master detail page?
`var mainPage = new XamarinFormsPageFactory().Init<MasterDetailViewModel, PFNavigationPage>();`works fine, but I want the navigation to be inside the master detail and not outside.

Giving more info:

You have a 
LoginView -> 
MasterDetailView
{
    Master = MenuView
    Detail = SomeNavigationPage 
}

How do you handle this scenario with PF?

**Comment by escamoteur** [comment]
As V3 brings major changes and enhancements to the API this thread is out of date any won't help much anymore. I open a new one,
