### ISSUE TITLE
Any demo for using IOC

### ISSUE THREAD

**Issue by jessejiang0214** [daniel-luberda/DLToolkit.PageFactory#50]
I saw TinyIoC in source, is there any sample code to show how to use it?

Another thing is xamvvm seems not support .NET Standard

**Comment by daniel-luberda** [comment]
- .NET Standard is supported in the prerelease nuget package. 
- Some IOC docs are here: https://github.com/xamvvm/xamvvm/wiki/IOC

Cheers :)
