### ISSUE TITLE
Wiki: Bootstrapping xamvvm: link error

### ISSUE THREAD

**Issue by miglrodri** [daniel-luberda/DLToolkit.PageFactory#51]
At the bootstrapping xamvvm section:
https://github.com/xamvvm/xamvvm/wiki/xamvvm-basics#bootstrapping-xamvvm

> More on initialization and registration you can find **here**

The page does not appear to exist.

Best regards.

**Comment by escamoteur** [comment]
Fixed!
Thansk for pointing out
