### ISSUE TITLE
How to use SetNewRootAndResetAsync to set new NavigationPage

### ISSUE THREAD

**Issue by drpulpie** [daniel-luberda/DLToolkit.PageFactory#52]
In App.cs
 ` factory.RegisterNavigationPage<MainNavigationPageModel>(() => this.GetPageFromCache<LoginModel>());
MainPage = this.GetPageFromCache<MainNavigationPageModel>() as NavigationPage;`

And then in LoginCommand I try to  `await this.SetNewRootAndResetAsync<MainPageModel>();`
It works but, if I navigate from main to another page I get error that I need to use Navigation page.

**Comment by escamoteur** [comment]
@drpulpie did you slove your problem?

**Comment by drpulpie** [comment]
Yes. Hate when you try and try and post in forum just as you see it from another way and solve it your self. Nice framework. Keep up the good work.

Skaffa Outlook för Android<https://aka.ms/ghei36>


________________________________

**Comment by adamhill** [comment]
What was the solution @drpulpie? I am having the same issue.
