### ISSUE TITLE
factory.RegisterTabbedPage can't use Pages from other assemblies

### ISSUE THREAD

**Issue by datoml** [daniel-luberda/DLToolkit.PageFactory#53]
Hello,
I found a strange issue today. My PageModel and Page are in different assemblies. Regarding to the wiki I registered the HomePage first and then added it to the TabPage.
It seems like the ReigsterTabbedPage ignores this completely because at runtime I get an null value exception.

This is the code I initialize the factory.

            var factory = new Xamvvm.XamvvmFormsRxUIFactory(this, 0, false);

            factory.RegisterPage<HomePageModel>(() => new HomePageModel(), () => new HomePage());

            factory.RegisterTabbedPage<TabbedPageModel>(new Type[]
            {
                typeof(HomePageModel)
            });

            XamvvmCore.SetCurrentFactory(factory);

            MainPage = this.GetPageFromCache<TabbedPageModel>() as TabbedPage;

Here's the complete example:
[https://github.com/datoml/XamvvmExample](https://github.com/datoml/XamvvmExample)

**Comment by xfer** [comment]
I had a similar issue (the `NullPointerException`), and I solved using the other `RegisterTabbedPage` method, like this : (note: not tested with your sample)

```csharp
            factory.RegisterTabbedPage<TabbedPageModel>(() =>
            {
                var list = new List<IBasePage<IBasePageModel>>();
                list.Add(this.GetPageAsNewInstance<HomePageModel>());

                return list;
            });

```

**Comment by datoml** [comment]
@xfer Thanks for this solution.
Regarding to my code the problem was that I had the number of cached item set to 0.
But your solution seems to be the answer if you don't want to cache pages.
