### ISSUE TITLE
Support Multi IoC Libraries

### ISSUE THREAD

**Issue by cbfrank** [daniel-luberda/DLToolkit.PageFactory#54]
I see the source code which hard code to create an instance of SimpleXamvvmIoC as the real ioc container and it use TinyIoc by hard code,  XamvvmIoC.Instance is internal so user can change it from their application code. Please change it to public so that user can implement IXamvvmIoC with their prefer Ioc library and specify it to XamvvmIoC.Instance

**Comment by daniel-luberda** [comment]
It's implemented in the newest alpha :)

**Comment by cbfrank** [comment]
Cool! Thanks for it.
