### ISSUE TITLE
Support for ContentView

### ISSUE THREAD

**Issue by nor0x** [daniel-luberda/DLToolkit.PageFactory#57]
Just stumbled upon this project, so far I really enjoy working with it. I'm wondering if there is support for ContentView as well. For example, I have a `ContentView` with a `ListView` displayed inside and I want to Bind the ItemSource to an `ObservableCollection` not in Code-Behind but in a `ViewModel`. How would DataBinding work in such scenario? Am I supposed to implement `IBasePage<SomePageModel>` or is there a specific Interface for `ContentViews`?

Thank you

**Comment by daniel-luberda** [comment]
@nor0x I just added navigation inside content view with a sample: 

[SampleNavigationViewNavigation.cs](https://github.com/xamvvm/xamvvm/blob/master/examples/ExamplesForms/Examples/Pages/SampleNavigationViewNavigation.cs)
[SampleNavigationViewPage.xaml](https://github.com/xamvvm/xamvvm/blob/master/examples/ExamplesForms/Examples/Pages/SampleNavigationViewPage.xaml)
[SampleNavigationViewPage.xaml.cs](https://github.com/xamvvm/xamvvm/blob/master/examples/ExamplesForms/Examples/Pages/SampleNavigationViewPage.xaml.cs)
[SampleNavigationViewPageModel.cs](https://github.com/xamvvm/xamvvm/blob/master/examples/ExamplesForms/Examples/Pages/SampleNavigationViewPageModel.cs)
[SampleFirstViewModel.cs](https://github.com/xamvvm/xamvvm/blob/master/examples/ExamplesForms/Examples/Views/SampleFirstViewModel.cs)

You must use latest prerelease package for this.

**Comment by daniel-luberda** [comment]
I am not quite sure if I understood what you want to achieve. Could you elaborate? 
Data binding always works, you only have to remember that your models should implement `INotifyPropertyChanged` (You can use `BaseModel` for that)

**Comment by nor0x** [comment]
I just got it, by looking at the new sample. Thank you
