### ISSUE TITLE
Navigation interceptors are not being called

### ISSUE THREAD

**Issue by marufbd** [daniel-luberda/DLToolkit.PageFactory#61]
I am using nuget pre release version and it seems among all the navigation interceptor methods only the 
NavigationPushed is called.

**Comment by daniel-luberda** [comment]
Hi @marufbd Could you write more details or give some code? 

Thanks

**Comment by marufbd** [comment]
@daniel-luberda 
The problem is navigating back from the page is done from actionbar back button or physical back button on android, question is in that case do i expect navigation event s be called.
I am only using PushPageAsync here and only NavigationPushed is being called, I am not calling PopAsync explicitly but when back button is clicked doesn't it automatically pop the current page?

I have a viewmodel:

public class MyViewModel: BasePageModel {
	public ICommand GotoAnotherPage=>new BaseCommand(async()=> {
		await this.PushPageAsNewInstanceAsync<AnotherPageViewModel>();
	);
	
	public override void NavigationInserted()
	{
		//never called when i come to this page or on navigate to another page 
		base.NavigationInserted();
	}
	public override void NavigationRemoved()
	{
		//never called when i come to this page or on navigate to another page 
		base.NavigationRemoved();
	}
	public override void NavigationRemovingFromCache()
	{
		//never called when i come to this page or on navigate to another page 
		base.NavigationRemovingFromCache();
	}
	public override void NavigationPopped()
	{
		//never called when i come to this page or on navigate to another page 
		base.NavigationPopped();
	}
	public override void NavigationPushed()
	{
		//only this is called when i come to this page
		base.NavigationPushed();
	}
}

I am trying to identifiy navigate away from current page to do something, OnDissappearing is not an option because Ondissappearing is called when app is minimized but remains in same screen/page.

**Comment by daniel-luberda** [comment]
Those method are called when you call `this.PopPageAsync()`, `this.RemovePageAsync()`, etc. Currently it's not possible to intercept other scenarios with Xamarin.Forms. See this: https://github.com/xamvvm/xamvvm/issues/6
