### ISSUE TITLE
Question: Comparing Freshmvvm features

### ISSUE THREAD

**Issue by EmilAlipiev** [daniel-luberda/DLToolkit.PageFactory#62]
Sorry if these are dummy question. As a freshmvvm user, I decided to use this library for my new project. Concept looks like pretty exciting but I am having difficulties to understand some things and I would like to ask a few questions. I think that there are many people like me switching from freshmvvm to xamvvm. So it can be also useful

1) Freshmvvm has viewmodel function to override ViewIsappearing and disappearing, I heavily used them. I couldnt see something similar. Should we just use standard XF ones?
2) Freshmvvm has 2 functions. Init and ReverseInit. Similar exists? ReverseInit is useful if a page is popped with data and retrieve in the previous page in the stack.

**Comment by daniel-luberda** [comment]
Hi @EmilAlipiev,

>Freshmvvm has viewmodel function to override ViewIsappearing and disappearing, I heavily used them. I couldnt see something similar. Should we just use standard XF ones?

Yes, but you need to use prerelease nuget (It'll be stable soon). Just implement `IPageVisibilityChange` or override methods which are already implemented in `BasePageModel` class. https://github.com/xamvvm/xamvvm/blob/master/source/Xamvvm.Core/Interfaces/IPageVisibilityChange.cs

> Freshmvvm has 2 functions. Init and ReverseInit. Similar exists? ReverseInit is useful if a page is popped with data and retrieve in the previous page in the stack.

I prefer strongly typed frameworks (which Xamvvm is). It allows you to create your own methods for such cases. Simple example here, but it's everything up to you: 

```C#
public class YourPageModel : BasePageModel
{
    Action<SomeStrongTypeNeeded> _onSuccessAction;

    public YourPageModel()
    {
        SuccessCommand = new BaseCommand(async (obj) => 
        {
           _onSuccessAction?.Invoke(Model)
           await this.PopPageAsync();
        });
    }

    public void Init(SomeStrongTypeNeeded obj, Action<SomeStrongTypeNeeded> onSuccessAction)
    {
        Model = obj;
        _onSuccessAction = onSuccessAction;
    }

    public SomeStrongTypeNeeded Model { get; private set; }

    public IBaseCommand SuccessCommand { get; set; }
}


//Then use it like that:

this.GetPageFromCache<YourPageModel>(v => v.Init(someStrongTypeNeededInstance), (obj) => { //TODO do something } ));
```

It allows easier error debugging, compile time error checking and code completion. You can even put it into some base class to have it in all page models.
