### ISSUE TITLE
XamarinFormsPageFactory doesn't Register the Page and PageModel To Ioc

### ISSUE THREAD

**Issue by cbfrank** [daniel-luberda/DLToolkit.PageFactory#64]
When call GetPageFromCache, the page and page mode are resolved from Ioc, this is ok for TinyIoC if the type is not registered, but if user implement their Ioc service with other Ioc library (such as autofac), the resolve will get exception if the type is not registered.
It would be better if XamarinFormsPageFactory constructor with automaticAssembliesDiscovery to true can register the found page and page mode type into Ioc service.

**Comment by daniel-luberda** [comment]
Hi @cbfrank 

You can use your own IoC: 

- implement `IXamvvmIoC`
- Set `XamvvmIoC.Instance = new YourCustomIoCImpl()`
