### ISSUE TITLE
PageFactoryPopping not called

### ISSUE THREAD

**Issue by escamoteur** [daniel-luberda/DLToolkit.PageFactory#7]
Hi Daniel,

I now decided to go for a pure Code BasePage:

```
namespace BREADy.Views
{
    public class CRUDBasePage<TViewModel> : PFContentPage<TViewModel> where TViewModel : CRUDBaseViewModel, INotifyPropertyChanged
    {
        public CRUDBasePage()
        {
            SetBinding(Page.TitleProperty, new Binding("PageTitle"));
        }


        public override bool PageFactoryPopping()
        {
            ViewModel.OnPagePopping();
            return base.PageFactoryPopping();
        }

        protected override bool OnBackButtonPressed()
        {
            ViewModel.OnPagePopping();
            return base.OnBackButtonPressed();

        }

    }
}

```

Unfortunately PageFactoryPopping does not get called. OnBackButtonPressed is called.
Any idea?

**Comment by escamoteur** [comment]
Just found out, that PageFactoryPopping is called if I popp the Page by pressing the BackButton. But when I pop the Page with this.PageFactory.PopModalPageAsync(); it does not get called.

**Comment by escamoteur** [comment]
Just found out, that when the Page is popped

in

```
        public async Task<bool> PopModalPageAsync(bool resetViewModel = false, bool animated = true)
        {
            var page = NavigationPage.Navigation.ModalStack.LastOrDefault() as IBasePage<INotifyPropertyChanged>;

            if (page != null && page.PageFactoryPopping())
            {
                if (resetViewModel)
                    ResetPageViewModel(page);

                await NavigationPage.Navigation.PopModalAsync(animated);    
                page.PageFactoryPopped();

                return true;
            }

            return false;
        }

```

Page is not the top ModalPage but the NavigationPage below.

**Comment by daniel-luberda** [comment]
@escamoteur I'll check it today. I had a problem with my dev machine, so wasn't available for a few days.

**Comment by escamoteur** [comment]
Hi Daniel,

good to hear from you. I just found out what's happening. The reason I think is, that there is a Navigationpage below my ModalPage, which get's popped together with the ModalPage, as it should. The PageFactoringPopping of the NavigationPage is called indeed.

**Comment by daniel-luberda** [comment]
@escamoteur Nice to hear that you worked it out. That's an expected (Xamarin.Forms like) behaviour.

BTW: I plan to do some blog series about PageFactory. Do you have any ideas what informations / guides / Q&A could be useful for new users?

**Comment by escamoteur** [comment]
Hmm good question. I found it not too difficult. Have look at my questions.
